# Шаблон для values-secret.yaml (plaintext, в .gitignore).
# После заполнения — шифруем в values-secret.enc.yaml и коммитим *.enc.yaml.
#
#   cp values-secret.example.yaml values-secret.yaml
#   # отредактировать values-secret.yaml
#   sops --encrypt --age "$PUBKEY" \
#        --encrypted-regex '^(secrets|data)$' \
#        values-secret.yaml > values-secret.enc.yaml
#   rm values-secret.yaml
#   git add values-secret.enc.yaml
#
secrets:
    - name: ENC[AES256_GCM,data:8z79qpmApw==,iv:0uGsRrMVzkpN/WgR6fkyTmMRg5uVSGyZTWgsNUUkZkI=,tag:M1Ocnv0z7cyvn5esrE0R4A==,type:str]
      namespace: ENC[AES256_GCM,data:Z3CSDA68NNw=,iv:fB8snZAC5bCn0bLzjCzvWGv/muiDZtIAUb/tFcSR7tA=,tag:XtTw4Et4IASx/IOfSIwuyA==,type:str]
      data:
        DB_USER: ENC[AES256_GCM,data:xjXHT/o=,iv:SYPP9yCzXh/cS3mqYTu5rg5wYBVnkSzag+wyG6dXo+g=,tag:NHQth7Rhu5yWFwLYaJtpDQ==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:Bxb6LusWQ+Ka,iv:cNiZoROSNkZMfzFkD6DGh5aXoODRgIJmoHXxxV1cdmw=,tag:H/PPEreiz6ZGZpXXuTBfag==,type:str]
    - name: ENC[AES256_GCM,data:ZjMGfcAKsdsL,iv:cqh7dXwjjNQolZwwcXBecYae8HcIS8rgowWKOr8gzVg=,tag:p1DcZO+r6wpy+7xiR0ifpQ==,type:str]
      #ENC[AES256_GCM,data:d6DUQ0DD6XvMFVFohzIgLcIhRyd5g47nFt0SlFV9A/8KIYvRtj+pg0IyxdUS4fUOAJlaM9CxNMEnSh80TBBuDrPe/OKd84HXpg==,iv:hdG1JH9u94darPJsAKNvM7jaX2zG8rul1ptR5LQEanw=,tag:71eLt2jYsjM0dysc2V52EA==,type:comment]
      data:
        token: ENC[AES256_GCM,data:nZm/yuFlCAqlQCaNt5/V75k1zHjTkf0=,iv:rLEYRyLwwKiF1N8Z5Q0/RUuqvD6WzTHdMbn8wLV3gA8=,tag:GIgr+6CrFzsFxaTevi6Bcw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7hml8gfdw5y2cey8nwvu97y87phrqpa2y478puk7yll3sa9cfss9jfvhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByTzJhdTVWUXdnaDBwb1Uv
            QzVMSHFQc0pCdG5Jc0hJM1hYZ2pINjU3cFEwClIrckgvTlBxSm5zMDFya1MvVXdv
            Y1lRTVJDSXNKTFVvc2FmVWJRTzloSkEKLS0tIGwyUUV1YnB1S04wYmVEWUIvV3hm
            Q0c3NUxDQk9BemlWbUd5Uyt6ZE1YUzgKBhackpIlcu+dfXyQIVzcXgh2f5Qu8BLF
            g7QMH6+UYN3PZ7zE2jxiX6QLHmPzHfNNsthBIv2GbfmkRIEnA9l9mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T09:32:35Z"
    mac: ENC[AES256_GCM,data:MtyqWV7rgWJ/Nyc73I6N0qetqSLIyJdjpcNJChlerM8Sdv3cSqZWPJGSfKLj6F6BrKZpciCIzVsFu0h/q+gudXm+I9o4TCI4Tcsg0DLfo3tQ4YhOYMHYPU874cbokn2T7t/Lch1sTzVt4UbXnLAJXRJ5nEOdU2wYdzrKvak9Fns=,iv:BFZd561jJ8/+Ps2PtlQVfUX3ZUMfu6bDgh4BgNk7hfI=,tag:ckYy6sFDGmEC6zaE/rc91w==,type:str]
    pgp: []
    encrypted_regex: ^(secrets|data)$
    version: 3.9.1
