# Шаблон для values-secret.yaml (plaintext, в .gitignore).
# После заполнения — шифруем в values-secret.enc.yaml и коммитим *.enc.yaml.
#
#   cp values-secret.example.yaml values-secret.yaml
#   # отредактировать values-secret.yaml
#   sops --encrypt --age "$PUBKEY" \
#        --encrypted-regex '^(secrets|data)$' \
#        values-secret.yaml > values-secret.enc.yaml
#   rm values-secret.yaml
#   git add values-secret.enc.yaml
#
secrets:
    - name: ENC[AES256_GCM,data:WB4yigvmWw==,iv:0fcSkX3zPqklEZuR4KmT8PFbjk6gjQbej/EJ2p9YPkQ=,tag:DdLRQfpJimq/X5bJC36PGg==,type:str]
      data:
        DB_USER: ENC[AES256_GCM,data:KS0My78=,iv:gr9Fuin9TpXYyGXTSCRneNzIkpJ+PF/PFowHa/+vmDE=,tag:eQQAISgO29ZAMOTKntZ+pw==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:N4o3EXcE2nXC,iv:ZAie7+tiHTRg5ODonoNbAklSD1uQlbU0yhw/K+bAf/8=,tag:9tyv58/nn0bJpsVqoLI+0A==,type:str]
    - name: ENC[AES256_GCM,data:+iwRFt3o1l8m,iv:Uyc+Je/2IsmzYygNOJfMCQrw7j+MwqmQc+ctPYGBacI=,tag:mQnmIHO/NiF7KF77x3/UQQ==,type:str]
      #ENC[AES256_GCM,data:w/YTEnh9NYCembO24Tsb/n7mIDUHxX+flpIXvxKOBYgqoHfRJ76KiBO/WoKvDrKO181++IV8OcBORpTQ5xPhlsr742HIM1dDnQ==,iv:Byus2W0q9mk+UGGdf7HI989yVGS/Ghy0DmfPyrOsIMo=,tag:grVdbvoCQ9Jcf+oQ8ptLVw==,type:comment]
      data:
        token: ENC[AES256_GCM,data:niZ7CPiV4wnxAoXS4PiHb+8XtfSK8Tg=,iv:HIlqXyGwwS0DVVCmHkZSUHSTC4K1UNpsl48KEb5Eryo=,tag:ny+Qxrtuackxg1RTLtWtlA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1e7hml8gfdw5y2cey8nwvu97y87phrqpa2y478puk7yll3sa9cfss9jfvhg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmWnAxWVZUYVZNdjdWYVpD
            dzJTUkx0ZmxFcFArQmt3ZzZDNWRiYXAxbEVvCjRNTUdmV1dCWExpTjBBK3ltdzFm
            R2RoNkFNZllHL2xmazRJUTlMMmhDaVkKLS0tIFBRb2locE4rMzhyeGUrMGtRK3Ey
            Nkp0d3VUS1U5UnF6MXBLMHRNemdFeUEKwYK0JGsWpQSv4mP5Et2C6aQTg0zvrK7K
            GK3LADbq35A9ziVwVOffo260n4LxpUMt+Yb8q+f4fUILKLJoZLylnw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T09:43:58Z"
    mac: ENC[AES256_GCM,data:DJzWRtNpnJNJq7O+ZOty/hnCiIp5QBEehfV4CQjcLiSjCgLfc53L+LPMOs50Qbrhn5tc4q+h9z9aTUAph8tz/w0gi1JAanun/AONkJfwp38fbsPSET6TuZCm5SC0O7+PlTjqYEmC1/aVNS0gValZpHhdSVSncPhxfPbWHYTw4tM=,iv:UBji0zU9kSSWWEHu0PqaQQe7BAF7qYxBT9VGj/+osnw=,tag:L7sfYzH9bejQis9VhQPuYA==,type:str]
    pgp: []
    encrypted_regex: ^(secrets|data)$
    version: 3.9.1
