# Неймспейс по умолчанию для всех Secret'ов из списка ниже. Можно переопределить
# пер-секрет полем `namespace`. Для AppProject infra все используемые ns
# должны быть в destinations (см. terraform/charts/argocd-bootstrap/templates/project-infra.yaml).
defaultNamespace: secrets


