# Шаблон для values-secret.yaml (plaintext, в .gitignore).
# После заполнения — шифруем в values-secret.enc.yaml и коммитим *.enc.yaml.
#
#   cp values-secret.example.yaml values-secret.yaml
#   # отредактировать values-secret.yaml
#   sops --encrypt --age "$PUBKEY" \
#        --encrypted-regex '^(secrets|data)$' \
#        values-secret.yaml > values-secret.enc.yaml
#   rm values-secret.yaml
#   git add values-secret.enc.yaml
#
secrets:
    - name: ENC[AES256_GCM,data:cTQ/IesJzg==,iv:Uy8BN8dwmJ3uA9aNe7GAJdkmi6cO3uewHFlkK9PdpfY=,tag:HR3UZAomqItu0YKQs/jw+Q==,type:str]
      namespace: ENC[AES256_GCM,data:0+o7enCEYOk=,iv:OuUkZJWLbVo0ULl010YlSlFh6LzypSF7fmxFwHQRhpQ=,tag:2xrECaALnL36eVab0UGQYQ==,type:str]
      data:
        DB_USER: ENC[AES256_GCM,data:r1UvdHc=,iv:ymb4RMaIWz0aHFOvu7LgKXes1Dk7a27fPvXaFpdt+Q4=,tag:I8UzsSW1Q0bMB4GkdPC4aA==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:IaowlCQykWC0,iv:dMdz3lZpZCJ33WTQJZMVXCs3Bo6+vGGBhdCf85RPqlw=,tag:FGwVx64zoRcmkG0KkrBxsA==,type:str]
    - name: ENC[AES256_GCM,data:HmqzSN/kR+Tw,iv:79qyGPLvnP14Lr8h6rcnY6/Wmgvu4dqjSV7ODDaGMEI=,tag:pQb+evdH+0UrYXPq3OhoAQ==,type:str]
      #ENC[AES256_GCM,data:j9OOsfwEpJ5/uoA9m1XfdUR3uP5E8KFfWxDG/g4aK4S2q2V+8YnkCAiJPdMdil7zsNJuEc6hQ5ZKV7LePbdWoTWV/ST/0qXxPg==,iv:Mbt7qVsc4g+IbO0tIw/T4k5zZNE1raWRvQjIssHSvBA=,tag:o2DPwPwPImaWbmrrfn7tCw==,type:comment]
      data:
        token: ENC[AES256_GCM,data:uVh3XV2iNSi68A62mTze6JKYE8puRnU=,iv:ZLQUNyoCg6CYfRyXV9NIVFywYDvM36bsHtlNickEoaM=,tag:+hI9D0pSCL1QvrjJnBn4eA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1h9ewwzzc428g49yp242z8wuszvql9d36yhgregym7rs3j4wezdfsewmzte
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvQ0ZBd1lELzlDZjRjZGFv
            Z3JsNUd6aWZpcXNaa0llS25LcEJjTUl5ZUhrCm9nakVkc2RBWFJZTE5UckhYcXd4
            U0U5UEI5ejhIMEtsYnkxZ0JXQkpkaTQKLS0tIGpiRHhydFZaNUhwNzRzUlJndmxJ
            c3lHWFkzUS92OU52RExMYjF2ZDFsVDAKdXoH5dBJZD6lJht8lkxBTDdbR7aFakom
            6qy4eyBKBaQud8FX+9wlAvRppSCO52/M43InAqwUZSmMTuvWUP+Qfg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-25T08:56:51Z"
    mac: ENC[AES256_GCM,data:MNJySys2c9unDnEBM7HgfnTA5uzXolGUOL44hq/OPMH1fFRKiGY/gGWe7umIxvWHpfnZVGEekQKuLS4iR01H9Q3RFaQmI6HtyG66IPR1AOLMQnRPIHTnO+rYxrMGVL3j5w/4GjGLPY8TOHuhwAAB4InDqFZNQFgvOB6xQMHApcU=,iv:OQdRuHq6NlLs5FWmQ+R7kQ/KniFqsZHhZyZ6HAJgido=,tag:0q8PHqn6UHVvQrs2FyZDvw==,type:str]
    pgp: []
    encrypted_regex: ^(secrets|data)$
    version: 3.9.1
