# Статический внешний IP, выданный Terraform'ом в Yandex Cloud.
# Прокидывается из ApplicationSet (terraform/charts/argocd-bootstrap/templates/appset-infra.yaml).
lbIp: ""

gateway-helm:
  config:
    envoyGateway:
      logging:
        level:
          default: info
