apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: public
spec:
  gatewayClassName: yc
  listeners:
    # HTTP listener остаётся на случай редиректа 80→443; ACME нам не нужен (DNS-01).
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: All
    - name: https
      port: 443
      protocol: HTTPS
      hostname: argocd.erlong.ru
      tls:
        mode: Terminate
        # Secret argocd-tls создаёт cert-manager (см. repo/infra/cert-manager) в этом же ns.
        certificateRefs:
          - kind: Secret
            group: ""
            name: argocd-tls
      allowedRoutes:
        namespaces:
          from: All
